### ISSUE TITLE
drugprot needs some polish

### ISSUE THREAD

**Issue by ArneBinder** [ArneBinder/pie-datasets#149]
This needs to be fixed/added:
- `_generate_example` is missing
- full cycle testing (example -> doc -> example)
- entity (and relation?) ids saved in the metadata should *not* be prefixed with the document id to better align with the [BRAT data format](https://brat.nlplab.org/standoff.html) (the data originates from that)

**Comment by kai-car** [comment]
Fixed through pull request #150
